name: Simple Sync and Merge

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  sync-and-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Pull from out/develop
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout develop
        git pull out develop --no-rebase
        git push origin develop

    - name: Merge to main
      run: |
        git checkout main
        git merge develop --no-ff -m "Auto-merge from develop"
        git push origin main
